### ISSUE TITLE
"out of memory"

### ISSUE THREAD

**Issue by rsnow** [Trellmor/bind-adblock#1]
I haven't gone into details, but if using all sources the host name lengths of some of them cause the zone not to load with "out of memory" message.  I just excluded everything that was > 50 char line length and all is well.  I'll do some additional testing to see what I find as the tip point.  bind 9.10.3 (ubuntu).

**Comment by Trellmor** [comment]
Probably a name longer the  255 characters or a label longer than 63 characters somewhere. Parsing the domain names with dnspython should get rid of invalid ones.
