### ISSUE TITLE
Optional check_zone & reload_zone

### ISSUE THREAD

**Issue by Schlesiger** [Trellmor/bind-adblock#12]
Greetings,

I am currently running bind-adblock inside a minimal Docker container. This container does not have access to the bind binaries. I would be nice to have options to skip both the check_zone and reload_zone steps. This way I can just receive a completed zone and overwrite my existing one.

Thanks!

**Comment by Trellmor** [comment]
I added a new switch "--no-bind" to disable bind zone file checking and loading.
