### ISSUE TITLE
Bind zones can handle wildcard

### ISSUE THREAD

**Issue by sudhaker** [Trellmor/bind-adblock#13]
Unlike host file, bind can handle wildcard so why don't we optimize the zone file for domains?

For example

```
$ cat adblock.rpz | wc -l
134973 (total lines)

$ grep .302br.net adblock.rpz | wc -l
17943
$ grep .hpg.com.br adblock.rpz | wc -l
878
```

Replacing these entries with followings will make things smaller, faster & much efficient.

*.302br.net IN CNAME .
*.hpg.com.br IN CNAME .

**Comment by Zjemm** [comment]
seems great, but how to automate it? you don't want to search for domains to be simplified by wildcards in the list manually.

also not all are due to be shortened via wildcards, as you might block to much

**Comment by Trellmor** [comment]
Combining entries will probably lead to overblocking. Because of that I don't plan to add it.
