### ISSUE TITLE
someonewhocares.org changed URL

### ISSUE THREAD

**Issue by ThorstenRhau** [Trellmor/bind-adblock#17]
https://www.someonewhocares.org/hosts/zero/

Hello
someonewhocares.org has recently being timing out for he. I changed the URL in your existing code to the URL listed above and got it working again. Please verify and change if you agree to my finding.
Thank you for providing this great script to the public.
With kind regards
Thorstne

**Comment by ThorstenRhau** [comment]
https://www.someonewhocares.org/hosts/zero/hosts

**Comment by Trellmor** [comment]
Thanks for reporting and submitting a fix!
