### ISSUE TITLE
Exclude domain list

### ISSUE THREAD

**Issue by takenek** [Trellmor/bind-adblock#2]
Hello
I just saw i go problem with HBO HO at home... after research i find:
HBOGO application connact to: level3cdn-hbogo-eu.secure.footprint.net if connect failed he don`t working.... i try watch Game of Throne S7E5 and this is impossible with this...

Please add option to create exclude domain list.
Best Regards
TaKeN

**Comment by Trellmor** [comment]
BIND can handle this, see http://www.zytrax.com/books/dns/ch7/rpz.html

You want to define a passthro response policy zone

```
// For AdBlock
response-policy {
	zone "rpz-whitelist.examle.com" policy passthro;
	zone "rpz.example.com";
};
```
`policy passthro` is the important bit. Make sure to add it before the other rpz.

Define the rpz whitelist zone in addition to the rpz zone
```
// Whitelist
zone "rpz-whitelist.example.com" {
	type master;
	file "/etc/bind/db.rpz-whitelist.example.com";
};
```

and add domain names you want to whitelist to `db.rpz-whitelist.example.com`.

```
@ 3600 IN SOA @ admin.example.com. 0 86400 7200 2592000 86400
@ 3600 IN NS ns.example.com.
footprint.net IN CNAME .
*.footprint.net IN CNAME .
```

This example will whitelist footprint.net and all it's subdomains. You can of course add only specific subdomains if you want.
