### ISSUE TITLE
Allow option to return NULL (0.0.0.0) rather than NXDOMAIN

### ISSUE THREAD

**Issue by braiam** [Trellmor/bind-adblock#21]
According to [PiHole experiments][1] when clients query return NXDOMAIN they don't immediately give up resolving the domain name. I'm unsure how complicated would be implementing this option.

 [1]: https://docs.pi-hole.net/ftldns/blockingmode/

**Comment by Trellmor** [comment]
Added a config option to `config.yml`. Set `blocking_mode`: `'NULL'` to return 0.0.0.0/::
