### ISSUE TITLE
This does not install correctly on various ubuntu versions

### ISSUE THREAD

**Issue by lee-rumble** [Trellmor/bind-adblock#27]
Was hoping to get this working, but its failed on ubuntu 14/16

# pip install -r requirements.txt 
Collecting certifi==2020.6.20 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl (156kB)
    100% |████████████████████████████████| 163kB 4.2MB/s 
Collecting chardet==3.0.4 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 6.0MB/s 
Collecting dnspython==2.0.0 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/67/d0/639a9b5273103a18c5c68a7a9fc02b01cffa3403e72d553acec444f85d5b/dnspython-2.0.0.zip (324kB)
    100% |████████████████████████████████| 327kB 2.8MB/s 
Collecting idna==2.10 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 7.8MB/s 
Collecting pathlib==1.0.1 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/ac/aa/9b065a76b9af472437a0059f77e8f962fe350438b927cb80184c32f075eb/pathlib-1.0.1.tar.gz (49kB)
    100% |████████████████████████████████| 51kB 7.8MB/s 
Collecting PyYAML==5.3.1 (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz (269kB)
    100% |████████████████████████████████| 276kB 3.2MB/s 
Collecting requests==2.24.0 (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/45/1e/0c169c6a5381e241ba7404532c16a21d86ab872c9bed8bdcd4c423954103/requests-2.24.0-py2.py3-none-any.whl (61kB)
    100% |████████████████████████████████| 71kB 8.0MB/s 
Collecting urllib3==1.25.10 (from -r requirements.txt (line 8))
  Downloading https://files.pythonhosted.org/packages/9f/f0/a391d1463ebb1b233795cabfc0ef38d3db4442339de68f847026199e69d7/urllib3-1.25.10-py2.py3-none-any.whl (127kB)
    100% |████████████████████████████████| 133kB 6.2MB/s 
Building wheels for collected packages: dnspython, pathlib, PyYAML
  Running setup.py bdist_wheel for dnspython ... done
  Stored in directory: /root/.cache/pip/wheels/33/c7/d2/367b914384b2ca7372006799bd16b52e307683bea1642da890
  Running setup.py bdist_wheel for pathlib ... done
  Stored in directory: /root/.cache/pip/wheels/f9/b2/4a/68efdfe5093638a9918bd1bb734af625526e849487200aa171
  Running setup.py bdist_wheel for PyYAML ... done
  Stored in directory: /root/.cache/pip/wheels/a7/c1/ea/cf5bd31012e735dc1dfea3131a2d5eae7978b251083d6247bd
Successfully built dnspython pathlib PyYAML
Installing collected packages: certifi, chardet, dnspython, idna, pathlib, PyYAML, urllib3, requests
Successfully installed PyYAML-5.3.1 certifi-2020.6.20 chardet-3.0.4 dnspython-2.0.0 idna-2.10 pathlib-1.0.1 requests-2.24.0 urllib3-1.25.10
You are using pip version 8.1.1, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@dns7:~/bind-adblock# ./update-zonefile.py --help
Traceback (most recent call last):
  File "./update-zonefile.py", line 33, in <module>
    import dns.zone
ImportError: No module named 'dns'
root@dns7:~/bind-adblock#

**Comment by ajdelgado** [comment]
Hi!
Consider using `pip3` or `python3 -m pip`.
The script is done for Python3 (check the shebang), and your system might use by default python 2.x still.
And also consider upgrading pip, you have v 8 and at the time you ran that, there was version 20. Quiet a jump.
Cheers!
