### ISSUE TITLE
[Request] Add Internet Storm Control 'Suspicious Domains' list

### ISSUE THREAD

**Issue by topranks** [Trellmor/bind-adblock#7]
Hey,

I happened to stumble across the following list:

https://isc.sans.edu/feeds/suspiciousdomains_Low.txt

(See https://isc.sans.edu/suspicious_domains.html for more info).  

Anyway when I added it to the script it pulled in an additional 3138 domains to my block (out of 3490 on the ISC list.)  So it seems to have a lot of unique entries not already covered.

I'm not sure how good it is as a list, I've had no trouble so far and they seem like a legit outfit.  Just a suggestion anyway.  BTW thanks for the project it is really useful and well put together !

Cathal.

**Comment by Trellmor** [comment]
Hi,

I'm glad you like my project. The ISC list looks good and I added it to the script.

Thanks.
