### ISSUE TITLE
Add custom domains to blacklist

### ISSUE THREAD

**Issue by dilworks** [Trellmor/bind-adblock#9]
First things first: THANKS for this project! I refuse to install adblockers on my clients (have so many devices at home it quickly becomes a maintenance nightmare to keep everything properly configured and up to date), so blocking ads at the DNS level makes a lot of sense to me.

Anyway, I've noticed that you document how to create a whitelist. However, what I want to know is how to do the inverse: aside of blocking ads and trackers, I want to add extra domains to the blocklist - I want to block Facebook and friends, and currently I achieve that using a custom zone for redirecting the facebook.com zone to a bogus IP inside my LAN. Is there a way to achieve the same with this script?

**Comment by jcestibariz** [comment]
That's a great idea, I'd love to use that list too! Can you share it, please?

You can add your custom zone to named.conf the same way you do with the black list generated by this script, that is add another entry to `response-policy` and add `allow-query { none; };` to your zone.

**Comment by jcestibariz** [comment]
Looks like this project has a comprehensive list of corporation domains https://github.com/jmdugan/blocklists

**Comment by dilworks** [comment]
Thanks for the tip!

I've migrated my solution from a custom zone (basically "let's pretend I'm the authority for facebook.com, so redirect it to my pixelserver") to this - I ended appending the blocklist entries (after being converted by your awk oneliner) to my main zone (that's because my routerbox is running some ancient Debian version with BIND 9.8, new enough for having RPZ support, but old enough for having not-so-great performance with more than one RPZ zone. And yes, I'm planning to upgrade Soon™).

Anyway, getting rid of ads PLUS Facebook feels great~

**Comment by Trellmor** [comment]
Took a while, but there is a way now:
Add a custom file list similar to blacklist.txt to [update-zonefile.py](https://github.com/Trellmor/bind-adblock/blob/master/update-zonefile.py#L54) or add the domains you want to block directly to blacklist.txt.
